title: <p align="center">   </p>

logo: "/images/profilepic.jpg?raw=true"
  
description:

  I am smart. 

  <p align="left">
   Hi! I'm an analytics professional who has a strong passion for delivering business insights and creating product innovation through the power of data. <br> 
   
   Currently, I'm a candidate for the Master of Science in Business Analytics at the University of Minnesota, Carlson School of Management.
  <br><br>
  </p>

theme: jekyll-theme-minimal
future: true
