title: <p align="center">   </p>

logo: "/images/profile.jpg?raw=true"

description:
  <h1 align="center"> Carol Ng </h1>
  <p align="center">
  <a href="https://www.linkedin.com/in/ngkalok/" target="_blank">LinkedIn</a> |
  <a href="https://github.com/ngkalokcarol?tab=repositories" target="_blank">GitHub</a>
  </p>
  
  
  <p align="left">
   Hi! I am a Data Science enthusiast with 6 years of experience in Quantitative Finance.
  <br><br> 
   Currently pursuing a Master Degree of Business Analytics in University of Minnesota, I focus on building Machine Learning models and utilizing Data Science technologies to solve real world problems. 
  <br><br>
  </p>

theme: jekyll-theme-minimal
future: true
