title: <p align="center">   </p>

logo: "/images/profile.jpg?raw=true"

description:
  <h1 align="center"><a href="https://ngkalokcarol.github.io/"> Carol Ng </a></h1>
  <p align="center">
  <a href="https://www.linkedin.com/in/ngkalok/">LinkedIn</a> |
  <a href="https://github.com/ngkalokcarol">GitHub</a>
  </p>
  
  
  <p align="left">
   Hi! I am a data science professional with 6 years of experience in Quantitative Finance. Currently pursuing a Master Degree of Business Analytics in University of Minnesota, I focus on building machine learning models and utilizing data science technologies to solve real world problems. 
   Here is my Data Science portfolio.
  <br><br>
  </p>

theme: jekyll-theme-minimal
future: true
